extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kush2021
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kushpadalia/
  tags:
    Array: array
    Binary Search: binarysearch
    Divide and Conquer: divideandconquer
    Dynamic Programming: dynamicprogramming
    Easy: easy
    Greedy: greedy
    Hard: hard
    Hash Table: hashtable
    Linked List: linkedlist
    Math: math
    Medium: medium
    Recursion: recursion
    Sliding Window: slidingwindow
    String: string
    Trie: trie
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Solutions:
      - Two Sum: solutions/two-sum.md
      - Add Two Numbers: solutions/add-two-numbers.md
      - Longest Substring Without Repeating Characters: solutions/longest-substring-without-repeating-characters.md
      - Median of Two Sorted Arrays: solutions/median-of-two-sorted-arrays.md
      - Longest Palindromic Substring: solutions/longest-palindromic-substring.md
      - Zigzag Conversion: solutions/zigzag-conversion.md
      - Reverse Integer: solutions/reverse-integer.md
      - String to Integer: solutions/string-to-integer.md
      - Palindrome Number: solutions/palindrome-number.md
      - Regular Expression Matching: solutions/regular-expression-matching.md
      - Container With Most Water: solutions/container-with-most-water.md
      - Integer to Roman: solutions/integer-to-roman.md
      - Roman to Integer: solutions/roman-to-integer.md
      - Longest Common Prefix: solutions/longest-common-prefix.md
  - Tags: tags.md
plugins:
  - search
  - tags:
      tags_file: tags.md
repo_url: https://github.com/kush2021/leetcode-solutions
repo_name: kush2021/leetcode-solutions
site_name: LeetCode Solutions
site_url: https://example.com/
theme:
  features:
    - content.code.copy
    - navigation.footer
    - header.autohide
  icon:
    tag:
      array: fontawesome/solid/layer-group
      binarysearch: fontawesome/solid/magnifying-glass
      divideandconquer: fontawesome/solid/chess-king
      dynamicprogramming: fontawesome/solid/table
      easy: fontawesome/solid/face-smile
      greedy: fontawesome/solid/sack-dollar
      hard: fontawesome/solid/face-sad-cry
      hashtable: fontawesome/solid/hashtag
      linkedlist: fontawesome/solid/link
      math: fontawesome/solid/calculator
      medium: fontawesome/solid/face-grin-beam-sweat
      recursion: fontawesome/solid/repeat
      slidingwindow: fontawesome/solid/window-restore
      string: fontawesome/solid/file-word
      trie: fontawesome/solid/tree
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light-blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
