extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kush2021
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kushpadalia/
  tags:
    Array: array
    Backtracking: backtracking
    Binary Search: binarysearch
    Divide and Conquer: divideandconquer
    Dynamic Programming: dynamicprogramming
    Easy: easy
    Greedy: greedy
    Hard: hard
    Hash Table: hashtable
    Heap: heap
    Linked List: linkedlist
    Math: math
    Medium: medium
    Merge Sort: mergesort
    Recursion: recursion
    Sliding Window: slidingwindow
    Sorting: sorting
    Stack: stack
    String: string
    Trie: trie
    Two Pointers: twopointers
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Solutions:
      - 1 - Two Sum: solutions/1-two-sum.md
      - 2 - Add Two Numbers: solutions/2-add-two-numbers.md
      - 3 - Longest Substring Without Repeating Characters: solutions/3-longest-substring-without-repeating-characters.md
      - 4 - Median of Two Sorted Arrays: solutions/4-median-of-two-sorted-arrays.md
      - 5 - Longest Palindromic Substring: solutions/5-longest-palindromic-substring.md
      - 6 - Zigzag Conversion: solutions/6-zigzag-conversion.md
      - 7 - Reverse Integer: solutions/7-reverse-integer.md
      - 8 - String to Integer: solutions/8-string-to-integer.md
      - 9 - Palindrome Number: solutions/9-palindrome-number.md
      - 10 - Regular Expression Matching: solutions/10-regular-expression-matching.md
      - 11 - Container With Most Water: solutions/11-container-with-most-water.md
      - 12 - Integer to Roman: solutions/12-integer-to-roman.md
      - 13 - Roman to Integer: solutions/13-roman-to-integer.md
      - 14 - Longest Common Prefix: solutions/14-longest-common-prefix.md
      - 15 - Three Sum: solutions/15-three-sum.md
      - 16 - Three Sum Closest: solutions/16-three-sum-closest.md
      - 17 - Letter Combinations of a Phone Number: solutions/17-letter-combinations-of-a-phone-number.md
      - 18 - Four Sum: solutions/18-four-sum.md
      - 19 - Remove Nth Node From End of List: solutions/19-remove-nth-node-from-end-of-list.md
      - 20 - Valid Parentheses: solutions/20-valid-parentheses.md
      - 21 - Merge Two Sorted Lists: solutions/21-merge-two-sorted-lists.md
      - 22 - Generate Parentheses: solutions/22-generate-parentheses.md
      - 23 - Merge K Sorted Lists: solutions/23-merge-k-sorted-lists.md
      - 24 - Swap Nodes in Pairs: solutions/24-swap-nodes-in-pairs.md
      - 25 - Reverse Nodes in K-Group: solutions/25-reverse-nodes-in-k-group.md
  - Tags: tags.md
plugins:
  - search
  - tags:
      tags_file: tags.md
repo_url: https://github.com/kush2021/leetcode-solutions
repo_name: kush2021/leetcode-solutions
site_name: LeetCode Solutions
site_url: https://example.com/
theme:
  features:
    - content.code.copy
    - navigation.footer
    - header.autohide
  icon:
    tag:
      array: fontawesome/solid/layer-group
      backtracking: fontawesome/solid/backward
      binarysearch: fontawesome/solid/magnifying-glass
      divideandconquer: fontawesome/solid/chess-king
      dynamicprogramming: fontawesome/solid/table
      easy: fontawesome/solid/face-smile
      greedy: fontawesome/solid/sack-dollar
      hard: fontawesome/solid/face-sad-cry
      hashtable: fontawesome/solid/hashtag
      heap: fontawesome/solid/people-line
      linkedlist: fontawesome/solid/link
      math: fontawesome/solid/calculator
      medium: fontawesome/solid/face-grin-beam-sweat
      mergesort: fontawesome/solid/code-merge
      recursion: fontawesome/solid/repeat
      slidingwindow: fontawesome/solid/window-restore
      sorting: fontawesome/solid/arrow-up-z-a
      stack: fontawesome/solid/cubes-stacked
      string: fontawesome/solid/file-word
      trie: fontawesome/solid/tree
      twopointers: fontawesome/solid/dice-two
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light-blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
