name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Image
      run: docker build . -t kush2021/leetcode-solutions:latest
    - name: Push the Docker Image
      run: docker push kush2021/leetcode-solutions:latest
